name: "Vprofile IAC Destroy"
on: 
  workflow_dispatch: 
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET8ACCESS_KEY: ${{ secrets.AWS_SECRET8ACCESS_KEY }}
  #s3 BUCKET FOR TF STATE
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks


jobs:
  terraform_destroy:
    name: "destroying infrastructure"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::152727848917:role/github-iac-access
        aws-region: ${{ env.AWS_REGION }}
    - name: checkout source code
      uses: actions/checkout@v4

    - name: Setup terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      # with:
        # terraform_version: 1.6.3
    - name: Get kube oonfig 'failure'
      id: getconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
  
    - name: Delete ingress controller
      run: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml

    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
          